# Generated by Django 4.0.5 on 2022-08-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_borrowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed',
            name='author',
        ),
        migrations.RemoveField(
            model_name='borrowed',
            name='description',
        ),
        migrations.RemoveField(
            model_name='borrowed',
            name='title',
        ),
        migrations.RemoveField(
            model_name='borrowed',
            name='updated',
        ),
        migrations.AddField(
            model_name='borrowed',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.book'),
        ),
        migrations.AddField(
            model_name='borrowed',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.role'),
        ),
        migrations.AddField(
            model_name='borrowed',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Returned', 'Returned')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='borrowed',
            name='time_borrowed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Book_requests',
        ),
    ]
