# Generated by Django 4.0.5 on 2022-08-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_fines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fines',
        ),
    ]
