# Generated by Django 4.0.5 on 2022-08-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_delete_borrowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='role',
        ),
    ]
