# Generated by Django 4.0.5 on 2022-08-07 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_order_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 7, 10, 52, 27, 571222, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_borrowed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 7, 10, 53, 11, 916676, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
