# Generated by Django 4.0.5 on 2022-08-10 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_book_order_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='student_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.role'),
        ),
    ]
