# Generated by Django 4.0.5 on 2022-08-10 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_order_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='student_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.role'),
        ),
    ]
