# Generated by Django 4.0.5 on 2022-08-19 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_fines_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 19, 14, 1, 42, 46799)),
            preserve_default=False,
        ),
    ]
